FilesystemCache:
  class: Pantono\Cache\Factory\FilesystemCacheFactory
  parameters:
    - $cache.filesystem.path
RedisCache:
  class: Pantono\Cache\Factory\RedisCacheFactory
  parameters:
    - $cache.redis.host
    - $cache.redis.port
ApplicationCache:
  class: Revolution\Cache\Factory\ApplicationCacheFactory
  aliases:
    - Pantono\Contracts\Application\Cache\ApplicationCacheInterface
  parameters:
    - "@Locator"
    - $cache.default
