FilesystemCache:
  class: Pantono\Cache\Factory\FilesystemCacheFactory
  parameters:
    - $cache.filesystem.path
  aliases:
    - Pantono\Contracts\Application\Cache\FilesystemCacheInterface
RedisCache:
  class: Pantono\Cache\Factory\RedisCacheFactory
  parameters:
    - $cache.redis.host
    - $cache.redis.port
ApplicationCache:
  class: Pantono\Cache\Factory\ApplicationCacheFactory
  aliases:
    - Pantono\Contracts\Application\Cache\ApplicationCacheInterface
  parameters:
    - "@ServiceLocator"
    - $cache.default
EphemeralCache:
  class: Pantono\Cache\Factory\EphemeralCacheFactory
  aliases:
    - Pantono\Contracts\Application\Cache\EphemeralCacheInterface
